### ISSUE TITLE
ENH: match only files and present as list (not tree)

### ISSUE THREAD

**Issue by Jython1415** [4imothy/gret#4]
## Problem

Awesome tool! This is already speeding up my development process. That said, this tool would be perfect for selecting and running tests that use a method *if* there was a way to list *only* files *without* the tree structure.

## Solution

- "Files" option: `-f` or `--files`. Show files without matching lines.
- Modify `-b` to be cumulative: `-b` is the current bland output, `-bb` or `-b -b` lists *only* the matching files without tree indentation.

### Alternatives Considered

I could actually just not be lazy and write something to parse the output from `gret`. However, I think this would be a really cool enhancement that would support an important use case.

**Comment by Jython1415** [comment]
Just wanted to add that the suggested implementation for the cumulative bland option is based on the not-so-uncommon cumulative implementation of `-v` (verbosity option). I think it would be good to follow this standard, but adding a separate option such as `--flat` would work as well.

**Comment by 4imothy** [comment]
Was implemented and merged to main. Let me know how it looks. The option is -f or --files

**Comment by Jython1415** [comment]
Sorry for the late reply! How can I build this locally to test it?

I reinstalled with `cargo` but I don't have the `--files` option

**Comment by 4imothy** [comment]
Should just be a
> git clone https://github.com/4imothy/gret.git
> cd gret
> cargo run `your regex` -f

**Comment by Jython1415** [comment]
My output ends up looking like this. Is this correct?

```text
(base) Joshua@Ganymede-2793 gret % cargo run "test" -f
   Compiling gret v0.1.1 (/Users/Joshua/Documents/_hobbies/_programming/gret)
    Finished dev [unoptimized + debuginfo] target(s) in 0.41s
     Running `target/debug/gret test -f`
(base) Joshua@Ganymede-2793 gret % 
```

**Comment by 4imothy** [comment]
Yeah that looks correct. In the gret folder there are no instances of the word test (at least in the files git is tracking). Try something like "path" as the regex which is in many files. You should just get a list of matched files.

**Comment by Jython1415** [comment]
Looks great! I got the following output.

```text
   Compiling gret v0.1.1 (/Users/Joshua/Documents/_hobbies/_programming/gret)
    Finished dev [unoptimized + debuginfo] target(s) in 1.63s
     Running `target/debug/gret path -f`
/Users/Joshua/Documents/_hobbies/_programming/gret/benchmarks/bench
/Users/Joshua/Documents/_hobbies/_programming/gret/src/searcher.rs
/Users/Joshua/Documents/_hobbies/_programming/gret/src/printer.rs
/Users/Joshua/Documents/_hobbies/_programming/gret/src/errors.rs
/Users/Joshua/Documents/_hobbies/_programming/gret/src/main.rs
/Users/Joshua/Documents/_hobbies/_programming/gret/src/args.rs
/Users/Joshua/Documents/_hobbies/_programming/gret/src/menu.rs
/Users/Joshua/Documents/_hobbies/_programming/gret/Cargo.toml
/Users/Joshua/Documents/_hobbies/_programming/gret/README.md
/Users/Joshua/Documents/_hobbies/_programming/gret/add_to_path.sh
```

Thank you for the help. Once the next update goes out, will this be feature be accessible when running `gret` normally?

**Comment by 4imothy** [comment]
Yes the version, 0.1.2 now has this feature
